### ISSUE TITLE
错误：播放b站视频使用补帧脚本spv或mvtools后报错，开启弹幕后再次按b无法关闭

### ISSUE THREAD

**Issue by ShaddockCyan** [itKelis/MPV-Play-BiliBili-Comments#1]
1.开启补帧脚本后，控制台报错信息如下：

[load_plus] 自动队列：当前目录无其它文件
 (+) Video --vid=1 (h264 1920x1080 30.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
File tags:
 Description: Bilibili VXCode Swarm Transcoder v0.7.6
Using hardware decoding (dxva2-copy).
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 nv12
AV: 00:00:02.067 / 00:07:21.764 (0%) A-V:  0.018 DS: 1.000/1 Dropped: 1 Cache: 9.7s/7MB
[autoconvert] Converting nv12 -> yuv420p
[vapoursynth] Script evaluation failed:
[vapoursynth] Python exception: 源帧率超过限制的范围，已临时禁用该脚本。
[vapoursynth]
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate
[vapoursynth]   File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate
[vapoursynth]   File "D:/Applications/PortableApps/MPV-lazy/portable_config/vs/mvtools-std.vpy", line 14, in <module>
[vapoursynth]     raise Warning("源帧率超过限制的范围，已临时禁用该脚本。")
[vapoursynth] Warning: 源帧率超过限制的范围，已临时禁用该脚本。
[vapoursynth]
[vapoursynth] could not init VS
Disabling filter vapoursynth.00 because it has failed.
AV: 00:00:07.717 / 00:07:21.764 (2%) A-V:  0.011 DS: 1.000/5 Dropped: 10 Cache: 22s/23MB

实测注释掉这行代码即可恢复正常，猜测这行代码限死了帧率导致补帧无法使用
#vf=lavfi="fps=fps=60:round=down"

2.开启弹幕后再按下b键无法关闭弹幕

**Comment by itKelis** [comment]
> 1.开启补帧脚本后，控制台报错信息如下：
> 
> [load_plus] 自动队列：当前目录无其它文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) File tags: Description: Bilibili VXCode Swarm Transcoder v0.7.6 Using hardware decoding (dxva2-copy). AO: [wasapi] 48000Hz stereo 2ch float VO: [gpu] 1920x1080 nv12 AV: 00:00:02.067 / 00:07:21.764 (0%) A-V: 0.018 DS: 1.000/1 Dropped: 1 Cache: 9.7s/7MB [autoconvert] Converting nv12 -> yuv420p [vapoursynth] Script evaluation failed: [vapoursynth] Python exception: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] Traceback (most recent call last): [vapoursynth] File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate [vapoursynth] File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate [vapoursynth] File "D:/Applications/PortableApps/MPV-lazy/portable_config/vs/mvtools-std.vpy", line 14, in [vapoursynth] raise Warning("源帧率超过限制的范围，已临时禁用该脚本。") [vapoursynth] Warning: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] could not init VS Disabling filter vapoursynth.00 because it has failed. AV: 00:00:07.717 / 00:07:21.764 (2%) A-V: 0.011 DS: 1.000/5 Dropped: 10 Cache: 22s/23MB
> 
> 实测注释掉这行代码即可恢复正常，猜测这行代码限死了帧率导致补帧无法使用 #vf=lavfi="fps=fps=60:round=down"
> 
> 2.开启弹幕后再按下b键无法关闭弹幕

你可以把帧率改高，60可以改成144等等

**Comment by itKelis** [comment]
> 1.开启补帧脚本后，控制台报错信息如下：
> 
> [load_plus] 自动队列：当前目录无其它文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) File tags: Description: Bilibili VXCode Swarm Transcoder v0.7.6 Using hardware decoding (dxva2-copy). AO: [wasapi] 48000Hz stereo 2ch float VO: [gpu] 1920x1080 nv12 AV: 00:00:02.067 / 00:07:21.764 (0%) A-V: 0.018 DS: 1.000/1 Dropped: 1 Cache: 9.7s/7MB [autoconvert] Converting nv12 -> yuv420p [vapoursynth] Script evaluation failed: [vapoursynth] Python exception: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] Traceback (most recent call last): [vapoursynth] File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate [vapoursynth] File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate [vapoursynth] File "D:/Applications/PortableApps/MPV-lazy/portable_config/vs/mvtools-std.vpy", line 14, in [vapoursynth] raise Warning("源帧率超过限制的范围，已临时禁用该脚本。") [vapoursynth] Warning: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] could not init VS Disabling filter vapoursynth.00 because it has failed. AV: 00:00:07.717 / 00:07:21.764 (2%) A-V: 0.011 DS: 1.000/5 Dropped: 10 Cache: 22s/23MB
> 
> 实测注释掉这行代码即可恢复正常，猜测这行代码限死了帧率导致补帧无法使用 #vf=lavfi="fps=fps=60:round=down"
> 
> 2.开启弹幕后再按下b键无法关闭弹幕

如果注释掉的话弹幕不会很卡吗

**Comment by ShaddockCyan** [comment]
> > 1.开启补帧后，性能报告信息如下：
> > [load_plus] 自动空：当前目录无其他文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) 文件标签： 说明： Bilibili VXCode Swarm Transcoder v0 AO：[sapi] 480000Hz VO：[gpu] 4800Hz 1920x1080 nv12AV：00:02.067 / 02.067 / 007:2112AV：00:02.067 / 007:218 DS：1% /1 脚本丢弃：1 缓存：9.7s/7MB [autoconvert] 转换 nv12 -> yuv420p [vapoursynth] 脚本评估失败：[vapoursynth] Python 异常：源帧率超过了的范围，已禁止禁止。 [vapoursynth] [ vapoursynth] Traceback（最近一次调用最后一次）：[vapoursynth] 文件“src\cython\vapoursynth.pyx”，第 2890 行，在 vapoursynth._vpy_evaluate [vapoursynth]“src\cython\vapoursynth.pyx”，第 2891 行文件，在 vapoursynth._vpy_evaluate [vapoursynth] 文件“D:/Applications /PortableApps/MPV-lazy/portable_config/vs/mvtools-std。
> > 实测代码确定死帧行代码可以正常运行，估计这行限掉率导致补帧无法使用#vflavfi=fps=fps=60:round=down
> > 2.开启弹幕后按下b键无法关闭弹幕
> 
> 如果评论掉话弹幕不会很卡吗

不会很卡的，因为开了补帧之后弹幕的帧率也被补上去了，我也试过把60改成120or144hz，但是还是相同的报错信息，同时补帧不生效

**Comment by itKelis** [comment]
> 1.开启补帧脚本后，控制台报错信息如下：
> 
> [load_plus] 自动队列：当前目录无其它文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) File tags: Description: Bilibili VXCode Swarm Transcoder v0.7.6 Using hardware decoding (dxva2-copy). AO: [wasapi] 48000Hz stereo 2ch float VO: [gpu] 1920x1080 nv12 AV: 00:00:02.067 / 00:07:21.764 (0%) A-V: 0.018 DS: 1.000/1 Dropped: 1 Cache: 9.7s/7MB [autoconvert] Converting nv12 -> yuv420p [vapoursynth] Script evaluation failed: [vapoursynth] Python exception: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] Traceback (most recent call last): [vapoursynth] File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate [vapoursynth] File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate [vapoursynth] File "D:/Applications/PortableApps/MPV-lazy/portable_config/vs/mvtools-std.vpy", line 14, in [vapoursynth] raise Warning("源帧率超过限制的范围，已临时禁用该脚本。") [vapoursynth] Warning: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] could not init VS Disabling filter vapoursynth.00 because it has failed. AV: 00:00:07.717 / 00:07:21.764 (2%) A-V: 0.011 DS: 1.000/5 Dropped: 10 Cache: 22s/23MB
> 
> 实测注释掉这行代码即可恢复正常，猜测这行代码限死了帧率导致补帧无法使用 #vf=lavfi="fps=fps=60:round=down"
> 
> 2.开启弹幕后再按下b键无法关闭弹幕

至于关闭弹幕，这个其实是按照加载字幕的方式来加载的，按下v就可以隐藏字幕

**Comment by itKelis** [comment]
> > > 1.开启补帧后，性能报告信息如下：
> > > [load_plus] 自动空：当前目录无其他文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) 文件标签： 说明： Bilibili VXCode Swarm Transcoder v0 AO：[sapi] 480000Hz VO：[gpu] 4800Hz 1920x1080 nv12AV：00:02.067 / 02.067 / 007:2112AV：00:02.067 / 007:218 DS：1% /1 脚本丢弃：1 缓存：9.7s/7MB [autoconvert] 转换 nv12 -> yuv420p [vapoursynth] 脚本评估失败：[vapoursynth] Python 异常：源帧率超过了的范围，已禁止禁止。 [vapoursynth] [ vapoursynth] Traceback（最近一次调用最后一次）：[vapoursynth] 文件“src\cython\vapoursynth.pyx”，第 2890 行，在 vapoursynth._vpy_evaluate [vapoursynth]“src\cython\vapoursynth.pyx”，第 2891 行文件，在 vapoursynth._vpy_evaluate [vapoursynth] 文件“D:/Applications /PortableApps/MPV-lazy/portable_config/vs/mvtools-std。
> > > 实测代码确定死帧行代码可以正常运行，估计这行限掉率导致补帧无法使用#vflavfi=fps=fps=60:round=down
> > > 2.开启弹幕后按下b键无法关闭弹幕
> > 
> > 
> > 如果评论掉话弹幕不会很卡吗
> 
> 不会很卡的，因为开了补帧之后弹幕的帧率也被补上去了，我也试过把60改成120or144hz，但是还是相同的报错信息，同时补帧不生效

那这个补帧可能就把弹幕一起补帧了，那你就把他注释掉把，没有什么影响的
我其实对这个mpv不太了解，这个只是看着官方文档写出来的插件，只能勉强称为玩具哈哈哈哈哈哈

**Comment by ShaddockCyan** [comment]
> > 1.开启补帧脚本后，控制台报错信息如下：
> > [load_plus] 自动队列：当前目录无其它文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) File tags: Description: Bilibili VXCode Swarm Transcoder v0.7.6 Using hardware decoding (dxva2-copy). AO: [wasapi] 48000Hz stereo 2ch float VO: [gpu] 1920x1080 nv12 AV: 00:00:02.067 / 00:07:21.764 (0%) A-V: 0.018 DS: 1.000/1 Dropped: 1 Cache: 9.7s/7MB [autoconvert] Converting nv12 -> yuv420p [vapoursynth] Script evaluation failed: [vapoursynth] Python exception: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] Traceback (most recent call last): [vapoursynth] File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate [vapoursynth] File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate [vapoursynth] File "D:/Applications/PortableApps/MPV-lazy/portable_config/vs/mvtools-std.vpy", line 14, in [vapoursynth] raise Warning("源帧率超过限制的范围，已临时禁用该脚本。") [vapoursynth] Warning: 源帧率超过限制的范围，已临时禁用该脚本。 [vapoursynth] [vapoursynth] could not init VS Disabling filter vapoursynth.00 because it has failed. AV: 00:00:07.717 / 00:07:21.764 (2%) A-V: 0.011 DS: 1.000/5 Dropped: 10 Cache: 22s/23MB
> > 实测注释掉这行代码即可恢复正常，猜测这行代码限死了帧率导致补帧无法使用 #vf=lavfi="fps=fps=60:round=down"
> > 2.开启弹幕后再按下b键无法关闭弹幕
> 
> 至于关闭弹幕，这个其实是按照加载字幕的方式来加载的，按下v就可以隐藏字幕

哇厉害👍，原来是靠字幕加载的，实测关闭字幕可行，谢谢啦

**Comment by ShaddockCyan** [comment]
> > > > 1.开启补帧后，性能报告信息如下：
> > > > [load_plus] 自动空：当前目录无其他文件 (+) Video --vid=1 (h264 1920x1080 30.000fps) (+) Audio --aid=1 (aac 2ch 48000Hz) 文件标签： 说明： Bilibili VXCode Swarm Transcoder v0 AO：[sapi] 480000Hz VO：[gpu] 4800Hz 1920x1080 nv12AV：00:02.067 / 02.067 / 007:2112AV：00:02.067 / 007:218 DS：1% /1 脚本丢弃：1 缓存：9.7s/7MB [autoconvert] 转换 nv12 -> yuv420p [vapoursynth] 脚本评估失败：[vapoursynth] Python 异常：源帧率超过了的范围，已禁止禁止。 [vapoursynth] [ vapoursynth] Traceback（最近一次调用最后一次）：[vapoursynth] 文件“src\cython\vapoursynth.pyx”，第 2890 行，在 vapoursynth._vpy_evaluate [vapoursynth]“src\cython\vapoursynth.pyx”，第 2891 行文件，在 vapoursynth._vpy_evaluate [vapoursynth] 文件“D:/Applications /PortableApps/MPV-lazy/portable_config/vs/mvtools-std。
> > > > 实测代码确定死帧行代码可以正常运行，估计这行限掉率导致补帧无法使用#vflavfi=fps=fps=60:round=down
> > > > 2.开启弹幕后按下b键无法关闭弹幕
> > > 
> > > 
> > > 如果评论掉话弹幕不会很卡吗
> > 
> > 
> > 不会很卡的，因为开了补帧之后弹幕的帧率也被补上去了，我也试过把60改成120or144hz，但是还是相同的报错信息，同时补帧不生效
> 
> 那这个补帧可能就把弹幕一起补帧了，那你就把他注释掉把，没有什么影响的 我其实对这个mpv不太了解，这个只是看着官方文档写出来的插件，只能勉强称为玩具哈哈哈哈哈哈

嗯嗯好的，已经很厉害了，不用谦虚🤣，弹幕效果非常好

**Comment by itKelis** [comment]
> 
谢谢鼓励，有什么好的想法尽管提出来哦
