### ISSUE TITLE
字幕可以在黑边显示吗？

### ISSUE THREAD

**Issue by PumpkinSin** [itKelis/MPV-Play-BiliBili-Comments#11]
用的mpvnet，在字幕设置里能选黑边显示的都选了，但好像没啥用

**Comment by itKelis** [comment]
> 用的mpvnet，在字幕设置里能选黑边显示的都选了，但好像没啥用

好像是不行的，mpv的渲染范围只有画面，黑边部分是不渲染的

**Comment by 20NE** [comment]
mpv 字幕可在底部顯示，設置：
```
sub-use-margins=yes 
sub-margin-y=10
```
但不知道彈幕是否可在左右黑边顯示
