### ISSUE TITLE
能不能直接适配链接ytdl解析的链接，而不通过脚本

### ISSUE THREAD

**Issue by sunjanesy** [itKelis/MPV-Play-BiliBili-Comments#15]
如我写的这个讨论所述，我希望可以直接通过链接解析把xml转化成ass弹幕
因为ytdl本身就可以配置cookies
https://github.com/hooke007/MPV_lazy/discussions/308

**Comment by itKelis** [comment]
这个脚本通过接收视频的cid号，从https://comment.bilibili.com直接下载视频的xml弹幕，需要解决的就是如何向脚本传送自定义参数cid。
通过ytdl解析之后mpv得到的地址是域名为bilivideo的视频流地址，并非带有bv号的视频主页地址，无法通过视频流地址找到视频对应的BV号与cid，所以我觉得并不可行

**Comment by sunjanesy** [comment]
有人在讨论区提供了一个第三方编译的yt-dl,可以不用任何脚本实现脚本解析了
