### ISSUE TITLE
加载失败怎么办？

### ISSUE THREAD

**Issue by xlxb1001** [itKelis/MPV-Play-BiliBili-Comments#16]
![QQ截图20230524040625](https://github.com/itKelis/MPV-Play-BiliBili-Comments/assets/101014731/747c4669-8db7-4c65-8e40-9e909e60567a)

**Comment by limoren123** [comment]
我个人发现的情况是如果解压MPV播放器文件夹在C:\Program Files或者C:\Program Files (x86)，会因为权限问题 无法更新bilibili.ass文件导致一直显示的默认的测试弹幕，直接放到C:\mpvnet，完美解决这个问题。之前看建议也是说放在c盘 及用户文件夹下，可以试试看

同理中文目录好像也不行

**Comment by itKelis** [comment]
> ![QQ截图20230524040625](https://user-images.githubusercontent.com/101014731/240407445-747c4669-8db7-4c65-8e40-9e909e60567a.png)

应该在scripts目录下新建一个名为 bilibiliAssert 的文件夹，并将Danmu2Ass.exe和main.lua放在里面，在mpv的scripts目录下，每一个文件夹都视为一个插件。
