### ISSUE TITLE
如何自定义弹幕字体和大小呢

### ISSUE THREAD

**Issue by Ahiok** [itKelis/MPV-Play-BiliBili-Comments#19]
py文件完全看不懂，搜索替换了几个font相关的字体，但是保存好后弹幕还是黑体粗字

**Comment by Ahiok** [comment]
# 弹幕字体
    parser.add_argument('-fn', '--font', metavar=_('FONT'), help=_('Specify font face [default: %s]') % _('(FONT) FangSong')[7:], default=_('(FONT) FangSong')[7:])
    # 弹幕字体大小
    parser.add_argument('-fs', '--fontsize', metavar=_('SIZE'), help=(_('Default font size [default: %s]') % 25), type=float, default=50.0) # initial = 25.0

**Comment by itKelis** [comment]
Add in line 37-52 of main.lua
```
local arg = {'python', py_path, '-d', directory,
-- set screen resolution (default 1920x1080)
'-s', '1920x1080',
-- set font size (default 37.0)
'-fs', '37.0',
-- Set the bullet chatting opacity (default 0.95)
'-a', '0.95',
-- The duration of the scrolling barrage display (default 10 seconds)
'-dm', '10.0',
-- The duration of the static bullet chatting display (default 5 seconds)
'-ds', '5.0',
-- The height of the blank space at the bottom (default 0, value 0.0-1.0)
'-p', '0',
        -- set the font

'-r',
cid,
}
```在main.lua的第37-52行添加
```
local arg = { 'python', py_path, '-d', directory, 
	-- 设置屏幕分辨率 （默认 1920x1080)
	'-s', '1920x1080',
	-- 设置字体大小    (默认 37.0)
	'-fs',  '37.0',
	-- 设置弹幕不透明度 (默认 0.95)
	'-a', '0.95',
	-- 滚动弹幕显示的持续时间 (默认 10秒)
	'-dm', '10.0',
	-- 静止弹幕显示的持续时间 (默认 5秒)
	'-ds', '5.0',
	-- 保留底部多少高度的空白区域 (默认　０, 取值0.0-1.0)
	'-p', '0',
        -- 设置字体
        '-fn', '字体名称'
	'-r',
	cid,
}
```

**Comment by qa19971109** [comment]
按照作者的方式在main.lua中修改透明度、字体大小等，在mpv中没有效果

**Comment by Ahiok** [comment]
> 在main.lua的第37-52行添加
> 
> ```
> local arg = { 'python', py_path, '-d', directory, 
> 	-- 设置屏幕分辨率 （默认 1920x1080)
> 	'-s', '1920x1080',
> 	-- 设置字体大小    (默认 37.0)
> 	'-fs',  '37.0',
> 	-- 设置弹幕不透明度 (默认 0.95)
> 	'-a', '0.95',
> 	-- 滚动弹幕显示的持续时间 (默认 10秒)
> 	'-dm', '10.0',
> 	-- 静止弹幕显示的持续时间 (默认 5秒)
> 	'-ds', '5.0',
> 	-- 保留底部多少高度的空白区域 (默认　０, 取值0.0-1.0)
> 	'-p', '0',
>         -- 设置字体
>         '-fn', '字体名称',
> 	'-r',
> 	cid,
> }
> ```

[main+py.zip](https://github.com/itKelis/MPV-Play-BiliBili-Comments/files/12707760/main%2Bpy.zip)
作者您好，我替换修改了一下main文件和py文件，生成的新弹幕文件内字号为50，字体确实指定为微软雅黑了（Style: Danmaku2ASS_53be, Microsoft YaHei, 50, &H0DFFFFFF, &H0DFFFFFF, &H0D000000, &H0D000000, 1, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 2, 0, 7, 0, 0, 0, 0）,但mpv内播放只有字号大小生效，字体还是黑体，请问能抽空检查一下是什么问题吗，劳力
