### ISSUE TITLE
保留底部多少高度的空白区域似乎有bug

### ISSUE THREAD

**Issue by Kyomaros** [itKelis/MPV-Play-BiliBili-Comments#24]
如果不设置为0的话，将不会生成ass弹幕文件

**Comment by Thintime1998** [comment]
是的，python文件里把type=int改成type=float类型后也会失效，望解决

**Comment by Thintime1998** [comment]
找到解决方法了，那个数字不是0-1，按照你的屏幕分辨率改就行了。例如1080的屏幕只显示1/4，改成810就行了
