### ISSUE TITLE
支援巴哈動畫瘋彈幕

### ISSUE THREAD

**Issue by s594569321** [itKelis/MPV-Play-BiliBili-Comments#28]
作者您好，最近因自己有需求加上沒有找到別人有寫，利用您的部份 code 製作了支援巴哈動畫瘋的相同功能腳本

請問允許開源嗎? ( 我是 github 新手，有什麼沒注意到的問題務必告知, 謝謝!! )

目前的 Private Repo:  https://github.com/s594569321/MPV-Play-BAHA-Comments

**Comment by itKelis** [comment]
可以的，我最近工作比较忙，没有什么精力更新这个代码了:)

**Comment by s594569321** [comment]
太好了
感謝！！
