### ISSUE TITLE
linux上路径错误的问题

### ISSUE THREAD

**Issue by slimx** [itKelis/MPV-Play-BiliBili-Comments#3]
在`main.lua` 的34行的`\\Danmu2Ass.py` 以及`Danmu2Ass.py`的542行的`\\bilibili.ass`
在linux下运行报错，改成`/`就正常了

**Comment by itKelis** [comment]
啊对的，是我疏忽了，现在应该正常了

**Comment by slimx** [comment]
呃，Danmu2Ass.py文件还没改呢

**Comment by itKelis** [comment]
> 呃，Danmu2Ass.py文件还没改呢

啊啊啊，已经改了，现在好了
