### ISSUE TITLE
DeprecationWarning: ssl.PROTOCOL_TLS is deprecated

### ISSUE THREAD

**Issue by liJie-wk** [itKelis/MPV-Play-BiliBili-Comments#30]
![image](https://github.com/itKelis/MPV-Play-BiliBili-Comments/assets/57932868/8d1dbdb4-c47b-4ab0-837c-1ba9b51c0e2a)

**Comment by verygoodlee** [comment]
DeprecationWarning只是个过时警告，之前也会报，跟他无关，
关键是下面的`urllib.error.HTTPError: HTTP Error 412: Precondition Failed`报错。

随便找了个cid，用浏览器是可以查看xml弹幕的：https://comment.bilibili.com/1536612379.xml ，
但是python程序下载就一直报错，应该是b站的弹幕下载服务端更新了，做了什么限制。

用NDM下载工具也会报错
![屏幕截图 2024-05-08 215838](https://github.com/itKelis/MPV-Play-BiliBili-Comments/assets/45035465/1ba6e8d8-78e0-4812-b0bd-97510677dc44)

用迅雷能下载，但是打开是乱码

**Comment by liJie-wk** [comment]
> DeprecationWarning只是个过时警告，之前也会报，跟他无关， 关键是下面的`urllib.error.HTTPError: HTTP Error 412: Precondition Failed`报错。
> 
> 随便找了个cid，用浏览器是可以查看xml弹幕的：https://comment.bilibili.com/1536612379.xml ， 但是python程序下载就一直报错，应该是最近b站的弹幕下载服务端更新了，做了什么限制。

看来这个问题要等一段时间才会有解决办法了

**Comment by verygoodlee** [comment]
试试这个itKelis/MPV-Play-BiliBili-Comments#31，我这里可以了

**Comment by liJie-wk** [comment]
> 试试这个#31，我这里可以了

原来是这个原因，解决了！我还以为是请求太频繁才这样，又学到了
