### ISSUE TITLE
弹幕无法正常拉取

### ISSUE THREAD

**Issue by Stardust911** [itKelis/MPV-Play-BiliBili-Comments#37]
请问组作者b站弹幕无法正常拉取，之前替换过你上传的两个插件，按钮是灰色的，试过关闭字幕也不行，系统window11，其他都正常，麻烦你了

**Comment by Stardust911** [comment]
![Uploading 微信图片_20240804223454.png…]()

**Comment by Stardust911** [comment]
![Uploading 微信图片_20240804223454.png…]()

**Comment by dyphire** [comment]
下载更新 main.lua 和 Danmu2Ass.py 文件后不起作用？
按钮是灰色的是什么意思？这个脚本不涉及任何 GUI 控件

**Comment by Stardust911** [comment]
> 下载更新 main.lua 和 Danmu2Ass.py 文件后不起作用？ 按钮是灰色的是什么意思？这个脚本不涉及任何 GUI 控件

嗯对，我替换了bilibiliAssert里面这两个文件，灰色就是点不动，以前是可以开关只是拉取的是错的。日志文件在哪里啊，截图上传不了

**Comment by dyphire** [comment]
我大概知道问题出在哪里了，更新你的 mpvnet 和 libmpv-2.dll 应该可以解决这个问题。你使用的 libmpv 太旧了，这是一个 luajit 兼容性问题

**Comment by dyphire** [comment]
由 #38 修复

**Comment by Stardust911** [comment]
> 我大概知道问题出在哪里了，更新你的 mpvnet 和 libmpv-2.dll 应该可以解决这个问题。你使用的 libmpv 太旧了，这是一个 luajit 兼容性问题

**Comment by Stardust911** [comment]
晕死，换了一个新的mpv，然后替换了你的两个插件，还是灰色的不可用了，放弃了。。。。我在想是不是play wtih mpv的问题，更新不了这个油猴插件

**Comment by dyphire** [comment]
> 晕死，换了一个新的mpv，然后替换了你的两个插件，还是灰色的不可用了，放弃了。。。。我在想是不是play wtih mpv的问题，更新不了这个油猴插件

在 mpvnet 的配置文件夹中找到 mpv.conf 文件，添加`log-file=~~/mpv.log`内容。再次测试并上传  mpv.conf 文件旁的 mpv.log 日志文件

**Comment by Stardust911** [comment]
[mpv.log](https://github.com/user-attachments/files/16497212/mpv.log)
还有更新不了play with mpv油猴插件，显示invalid script header。不知道和这个有无关系。

**Comment by dyphire** [comment]
> [mpv.log](https://github.com/user-attachments/files/16497212/mpv.log) 还有更新不了 play with mpv 油猴插件，显示 invalid script header。不知道和这个有无关系。

你 mpv 配置错误的地方也太多了，在哪乱抄的作业（
顺便从日志来看，你最开始发的截图控制台的报错确实由 #38 修复，现在不再报错
不生成弹幕的原因是你的 Play-With-MPV 脚本压根没传视频的 cid 参数过来，bilibiliAssert 就没下载到对应的弹幕自然无法加载，这和该脚本无关

**Comment by Stardust911** [comment]
额，我是从b站的https://space.bilibili.com/368780828，还有https://github.com/hkiceflow/mpv_video获取的，感觉都是大神不应该啊，他好像没有更新弹幕功能，他不重视，请问你有正确版本的吗，可以有偿

**Comment by dyphire** [comment]
b 站”大神“，不懂 mpv 参数的含义和作用的话不要乱抄，直接默参也比瞎抄强（

使用最新版 Play-With-MPV 油猴脚本和 bilibiliAssert 脚本无法复现你遇到的问题
![image](https://github.com/user-attachments/assets/77df111b-a8a0-40ad-8269-b14f714de2b1)
无法复制你的使用环境，只能说大概率不是脚本的问题

**Comment by Stardust911** [comment]
额，那作为小白该怎么办，我只有拿集成软件呐，因为集成着色器和补帧太复杂我不会，不是专业的，哭了。只是想简单的看个番而已。之前用的luckypuppy的mpv-lazy也不行

**Comment by Stardust911** [comment]
[mpv.log](https://github.com/user-attachments/files/16499177/mpv.log)
这才是替换了您的脚本日志

**Comment by Stardust911** [comment]
这才是替换了您的脚本日志
[Uploading mpv.log…]()

**Comment by Stardust911** [comment]
[mpv.log](https://github.com/user-attachments/files/16499196/mpv.log)

**Comment by Stardust911** [comment]
这才是替换了您的脚本日志

**Comment by dyphire** [comment]
> [mpv.log](https://github.com/user-attachments/files/16499196/mpv.log)

这次的日志有所不同了
```log
[   1.088][w][bilibiliAssert] 弹幕正在上膛 
[   1.088][d][cplayer] Run command: apply-profile, flags=64, args=[name="deband-bitrate", mode="apply"]
[   1.088][v][cplayer] Applying profile 'deband-bitrate'...
[   1.088][v][cplayer] Setting option 'deband' = 'yes' (flags = 4)
[   1.088][d][cplayer] Run command: subprocess, flags=64, args=[args="python,D:\\mpvnet\\portable_config\\scripts/bilibiliAssert\\Danmu2Ass.py,-d,\\,-s,1920x1080,-fn,sans-serif,-fs,50,-a,0.95,-dm,10,-ds,5,-flf,,-p,810,-r,875212290", playback_only="no", capture_size="67108864", capture_stdout="yes", capture_stderr="no", detach="no", env="", stdin_data="", passthrough_stdin="no"]
```
bilibiliAssert 脚本有正常获取到Play-With-MPV 油猴脚本传递的 cid 参数，但在执行 Danmu2Ass.py 时静默退出了
你本地是不是没有安装 python 环境？安装个 python 再试试：https://www.python.org/downloads/

**Comment by Stardust911** [comment]
![有](https://github.com/user-attachments/assets/d6341199-0c3c-4aef-bf76-dcdcdd3c3c11)
有的呀大佬，算了放弃了，不远程搞不清楚地，只有不用mpv看网页断了，就算是正常拉取也是满屏幕的弹幕看不清楚哈哈，只有看本地视频再用mpv进行超分好了，门槛太高了，希望以后有大佬做个完整一点的包。

**Comment by Stardust911** [comment]
![2](https://github.com/user-attachments/assets/ec94fcd9-5b36-4605-a340-b0c1a0164710)
灰色点不打开

**Comment by dyphire** [comment]
你的 mpvnet 文件夹里怎么还有 Implay 的包，两个 libmpv 客户端放一起了，哪个大聪明打的包（

**Comment by dyphire** [comment]
> > [mpv.log](https://github.com/user-attachments/files/16499196/mpv.log)
> 
> 这次的日志有所不同了
> 
> ```
> [   1.088][w][bilibiliAssert] 弹幕正在上膛 
> [   1.088][d][cplayer] Run command: apply-profile, flags=64, args=[name="deband-bitrate", mode="apply"]
> [   1.088][v][cplayer] Applying profile 'deband-bitrate'...
> [   1.088][v][cplayer] Setting option 'deband' = 'yes' (flags = 4)
> [   1.088][d][cplayer] Run command: subprocess, flags=64, args=[args="python,D:\\mpvnet\\portable_config\\scripts/bilibiliAssert\\Danmu2Ass.py,-d,\\,-s,1920x1080,-fn,sans-serif,-fs,50,-a,0.95,-dm,10,-ds,5,-flf,,-p,810,-r,875212290", playback_only="no", capture_size="67108864", capture_stdout="yes", capture_stderr="no", detach="no", env="", stdin_data="", passthrough_stdin="no"]
> ```
> 
> bilibiliAssert 脚本有正常获取到 Play-With-MPV 油猴脚本传递的 cid 参数，但在执行 Danmu2Ass.py 子进程命令时静默退出了 你本地是不是没有安装 python 环境？安装个 python 再试试：https://www.python.org/downloads/

等一下，你确定用的是 https://github.com/dyphire/MPV-Play-BiliBili-Comments/tree/compatibility 上最新的 main.lua？为什么你的`-d,\\,` 依然没有获取系统临时路径？你的系统环境变量里 TEMP 被删了？

**Comment by dyphire** [comment]
对 main.lua 进行以下修改再试试看：
```lua
        local danmaku_dir = os.getenv("TEMP") or utils.split_path(os.tmpname())
	if danmaku_dir:match("^\\") then
		danmaku_dir = mp.command_native({"expand-path", "~/AppData/Local/Temp"})
	end
```

**Comment by dyphire** [comment]
你这个日志里体现出来的问题真的很奇怪
```log
[   1.088][d][cplayer] Run command: script-message, flags=64, args=[args="thumbfast-info", args="{\"disabled\":true,\"available\":true,\"thumbnail\":\"C:\\\\Users\\\\Stardust\\\\AppData\\\\Local\\\\Temp\\\\thumbfast.out25680\",\"socket\":\"thumbfast25680\",\"width\":200,\"overlay_id\":42,\"height\":200}"]
```
注意看 thumbfast 这条日志信息，同样的 lua 临时路径获取方式， thumbfast 正确获取到了系统临时路径
```lua
if options.thumbnail == "" then
    if os_name == "windows" then
        options.thumbnail = os.getenv("TEMP").."\\thumbfast.out"
    else
        options.thumbnail = "/tmp/thumbfast.out"
    end
end
```
bilibiliAssert 的 main.lua 中同样使用 os.getenv("TEMP") 来获取 Windows 上的临时路径，为什么它没获取到？
检查你的 main.lua 代码，感觉不太对

**Comment by Stardust911** [comment]
[bilibiliAssert.zip](https://github.com/user-attachments/files/16500336/bilibiliAssert.zip)
![1](https://github.com/user-attachments/assets/14b9e191-c8ec-4088-a526-da65b00eb256)
文件包就是刚才提到up改的，b站有，改了还是不行呢，路径应该也没问题的。我可以给你原始包，这里上传不了那么大文件

**Comment by Stardust911** [comment]
或者qq远程看看也行

**Comment by dyphire** [comment]
> [bilibiliAssert.zip](https://github.com/user-attachments/files/16500336/bilibiliAssert.zip)

直接下载替换 [main.lua](https://github.com/dyphire/MPV-Play-BiliBili-Comments/blob/compatibility/scripts/bilibiliAssert/main.lua)，不要自己改，都改错了

**Comment by Stardust911** [comment]
[mpv.log](https://github.com/user-attachments/files/16511809/mpv.log)
gan感谢大佬，替换了还是不行哈哈，快成功的感觉了

**Comment by yl590** [comment]
我也是这样，试过mpv-config整合包和最新的mpvnet都不行
[mpv.log](https://github.com/user-attachments/files/16521058/mpv.log)

**Comment by itKelis** [comment]
> 我也是这样，试过mpv-config整合包和最新的mpvnet都不行 [mpv.log](https://github.com/user-attachments/files/16521058/mpv.log)

我下载了最新的mpvnet protable版本，也是正常加载，我看了一下你的log显示找不到bilibiliAssert.conf，你是不是没有把插件文件夹放置在script-opts文件夹下

**Comment by cjmornt** [comment]
> > 我也是这样，试过mpv-config整合包和最新的mpvnet都不行 [mpv.log](https://github.com/user-attachments/files/16521058/mpv.log)
> 
> 我下载了最新的mpvnet protable版本，也是正常加载，我看了一下你的log显示找不到bilibiliAssert.conf，你是不是没有把插件文件夹放置在script-opts文件夹下

问一下，我也是怎么用都读取不了弹幕，这个bilibiliAssert文件夹我是放在scripts里的，是放错了吗，但是放到script-opts文件夹就没有读取这个插件了，而且我的打开控制台会显示这个
![Uploading mpv_Z2qLwtmrCu.jpg…]()

**Comment by itKelis** [comment]
> > > 我也是这样，试过mpv-config整合包和最新的mpvnet都不行 [mpv.log](https://github.com/user-attachments/files/16521058/mpv.log)
> > 
> > 
> > 我下载了最新的mpvnet protable版本，也是正常加载，我看了一下你的log显示找不到bilibiliAssert.conf，你是不是没有把插件文件夹放置在script-opts文件夹下
> 
> 问一下，我也是怎么用都读取不了弹幕，这个bilibiliAssert文件夹我是放在scripts里的，是放错了吗，但是放到script-opts文件夹就没有读取这个插件了，而且我的打开控制台会显示这个 ![mpv_Z2qLwtmrCu](https://private-user-images.githubusercontent.com/83075323/356854944-16546e2e-01e4-4901-8540-f399dab6f6e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTA0ODAsIm5iZiI6MTcyMzM5MDE4MCwicGF0aCI6Ii84MzA3NTMyMy8zNTY4NTQ5NDQtMTY1NDZlMmUtMDFlNC00OTAxLTg1NDAtZjM5OWRhYjZmNmU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjODc5YzA2ZWU0NTE3MzdmMGNkMDU0NjE1ZWU5M2E2OTk2YjMxZWZhZTlmNmVmM2EyMzQwMjFjOTcyMDRhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oh9fDT3wzL7YeuHtX7gQOJJa2WMGrTXOd29UW3txIY)

我确实在mpv.net无法复现你们的问题，无论是使用portable还是正常模式，建议你新开一个帖子，将mpv.conf文件所有内容与你所安装的所有插件列出来。
另外，从你的截图上看似乎是你复制main.lua代码时出现问题，建议重新下载并main.lua文件

**Comment by cjmornt** [comment]
> > > > 我也是这样，试过mpv-config整合包和最新的mpvnet都不行 [mpv.log](https://github.com/user-attachments/files/16521058/mpv.log)
> > > 
> > > 
> > > 我下载了最新的mpvnet protable版本，也是正常加载，我看了一下你的log显示找不到bilibiliAssert.conf，你是不是没有把插件文件夹放置在script-opts文件夹下
> > 
> > 
> > 问一下，我也是怎么用都读取不了弹幕，这个bilibiliAssert文件夹我是放在scripts里的，是放错了吗，但是放到script-opts文件夹就没有读取这个插件了，而且我的打开控制台会显示这个 ![mpv_Z2qLwtmrCu](https://private-user-images.githubusercontent.com/83075323/356854944-16546e2e-01e4-4901-8540-f399dab6f6e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTA0ODAsIm5iZiI6MTcyMzM5MDE4MCwicGF0aCI6Ii84MzA3NTMyMy8zNTY4NTQ5NDQtMTY1NDZlMmUtMDFlNC00OTAxLTg1NDAtZjM5OWRhYjZmNmU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjODc5YzA2ZWU0NTE3MzdmMGNkMDU0NjE1ZWU5M2E2OTk2YjMxZWZhZTlmNmVmM2EyMzQwMjFjOTcyMDRhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oh9fDT3wzL7YeuHtX7gQOJJa2WMGrTXOd29UW3txIY)
> 
> 我确实在mpv.net无法复现你们的问题，无论是使用portable还是正常模式，建议你新开一个帖子，将mpv.conf文件所有内容与你所安装的所有插件列出来，或者列出下载mpv整合包的地址。
> 
> 另外，从你的截图上看似乎是你复制main.lua代码时出现问题，建议重新下载并覆盖main.lua文件，最新版本代码无论是放置在scripts文件夹还是script-opts文件夹，经过测试都是正常运行没有问题的。

确实是我之前文件可能有问题，我重新下了main文件，现在显示是这样的
![mpv_jm45SfzlKc](https://github.com/user-attachments/assets/ee3de5ab-79f2-432d-bd6b-a6e6948093d5)
，我等下发新帖子贴一下mpv。conf和插件

**Comment by itKelis** [comment]
> > > > > 我也是这样，试过mpv-config整合包和最新的mpvnet都不行 [mpv.log](https://github.com/user-attachments/files/16521058/mpv.log)
> > > > 
> > > > 
> > > > 我下载了最新的mpvnet protable版本，也是正常加载，我看了一下你的log显示找不到bilibiliAssert.conf，你是不是没有把插件文件夹放置在script-opts文件夹下
> > > 
> > > 
> > > 问一下，我也是怎么用都读取不了弹幕，这个bilibiliAssert文件夹我是放在scripts里的，是放错了吗，但是放到script-opts文件夹就没有读取这个插件了，而且我的打开控制台会显示这个 ![mpv_Z2qLwtmrCu](https://private-user-images.githubusercontent.com/83075323/356854944-16546e2e-01e4-4901-8540-f399dab6f6e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTA0ODAsIm5iZiI6MTcyMzM5MDE4MCwicGF0aCI6Ii84MzA3NTMyMy8zNTY4NTQ5NDQtMTY1NDZlMmUtMDFlNC00OTAxLTg1NDAtZjM5OWRhYjZmNmU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE1Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjODc5YzA2ZWU0NTE3MzdmMGNkMDU0NjE1ZWU5M2E2OTk2YjMxZWZhZTlmNmVmM2EyMzQwMjFjOTcyMDRhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oh9fDT3wzL7YeuHtX7gQOJJa2WMGrTXOd29UW3txIY)
> > 
> > 
> > 我确实在mpv.net无法复现你们的问题，无论是使用portable还是正常模式，建议你新开一个帖子，将mpv.conf文件所有内容与你所安装的所有插件列出来，或者列出下载mpv整合包的地址。
> > 另外，从你的截图上看似乎是你复制main.lua代码时出现问题，建议重新下载并覆盖main.lua文件，最新版本代码无论是放置在scripts文件夹还是script-opts文件夹，经过测试都是正常运行没有问题的。
> 
> 确实是我之前文件可能有问题，我重新下了main文件，现在显示是这样的 ![mpv_jm45SfzlKc](https://private-user-images.githubusercontent.com/83075323/356890312-ee3de5ab-79f2-432d-bd6b-a6e6948093d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTI0NDksIm5iZiI6MTcyMzM5MjE0OSwicGF0aCI6Ii84MzA3NTMyMy8zNTY4OTAzMTItZWUzZGU1YWItNzlmMi00MzJkLWJkNmItYTZlNjk0ODA5M2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE2MDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWY0YzM1ZDdiYzc2NDc5MzE2NTBlZTMyMWEwZTIxOWE5MWVlMmIxOGMyMzdiMDc1YWQwYjgwNDVmNDFhMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wzIakIUMG7_akTA57Ec-XMSI6x4dJae_xktAlLZBg38) ，我等下发新帖子贴一下mpv。conf和插件

这里显示mpv开启进程失败，可能是你的mpv配置有问题，需要提供mpv.conf
