### ISSUE TITLE
gwy15/danmu2ass 弹幕解析后端

### ISSUE THREAD

**Issue by skbeh** [itKelis/MPV-Play-BiliBili-Comments#4]
如题，使用 https://github.com/gwy15/danmu2ass 解析弹幕可以大幅提高弹幕解析速度，并且消除 python 依赖。
另外，assert 是 lua 内置函数，不应该覆盖。asset 的 typo？

**Comment by itKelis** [comment]
> typo

好的，非常感谢，函数名已经改了。

至于解析速度的话，因为这是个mpv插件，不存在批量解析弹幕文件的场景，再加上脚本是异步执行，我使用的也不是原版代码，修改了xml解析方式，已经快了很多，解析弹幕的时间可以忽略不计。

我分析过每个函数的执行时间，下载弹幕的延时已经比解析弹幕的时间长很多了，所以解析速度这个不是问题，就算提高百倍也几乎不可感知。

至于使用别人的程序，怎么说呢，能上github的一般都已经有python了吧，相对来说能直接找到这个仓库的大多数人已经可以做到开箱即用

对于mpv-lazy之类的集合包来说，已经自带了python解释器，这个更不是问题了

再者，因为上述 https://github.com/gwy15/danmu2ass 并没有添加任何开源许可，所以我如果直接打包他的二进制程序可能会涉及侵权，这就导致如果我修改代码使用这个二进制程序的话，还要麻烦你们自行下载。

**Comment by skbeh** [comment]
LICENSE 问题我去开了个 issue：https://github.com/gwy15/danmu2ass/issues/4
danmaku2ass 以 GPLv3 授权，所以你这个仓库也应该以 GPLv3 授权。

**Comment by skbeh** [comment]
@itKelis danmu2ass 现在以 MIT 协议授权。

**Comment by itKelis** [comment]
> 

好的，让我想想怎么修改，目前这个插件是通过视频的cid获取弹幕的，如果修改为danmu2ass的话要改很多东西，可能不会那么快完成。

**Comment by skbeh** [comment]
@itKelis 我建议通过 bilibili API 通过 BV 号获取 cid，这样也能兼容直接打开链接的情况。
如果使用 lua 实现的话，可能需要 JSON 库和 curl/lua-curl 库。

**Comment by skbeh** [comment]
~~或者用 rust 写 MPV 的 [C plugin](https://lib.rs/crates/mpv-client) ~~

**Comment by itKelis** [comment]
> @itKelis 我建议通过 bilibili API 通过 BV 号获取 cid，这样也能兼容直接打开链接的情况。 如果使用 lua 实现的话，可能需要 JSON 库和 curl/lua-curl 库。

请问一下你是怎么发现这个插件的呢，这个插件的正确使用方法应该配合 https://github.com/LuckyPuppy514/Play-With-MPV 脚本使用，这个插件的作用就是获取此油猴脚本传递的视频cid，然后根据cid直接下载弹幕文件，插件并不知道视频的BV号，mpv获取的播放链接已经是可以直接播放的bilivideo.com视频链接

**Comment by itKelis** [comment]
> 或者用 rust 写 MPV 的 [C plugin](https://lib.rs/crates/mpv-client)

只能让那个danmu2ass的作者支持一下通过cid获取视频弹幕了，因为本来弹幕就是通过cid请求获取的

**Comment by skbeh** [comment]
@itKelis 我知道这一点，但是我认为不应该和浏览器/网页版强耦合。

**Comment by itKelis** [comment]
> @itKelis 我知道这一点，但是我认为不应该和浏览器/网页版强耦合。

其实我做这个插件只是因为那个油猴脚本比较好用

**Comment by skbeh** [comment]
> > 或者用 rust 写 MPV 的 [C plugin](https://lib.rs/crates/mpv-client)
> 
> 只能让那个danmu2ass的作者支持一下通过cid获取视频弹幕了，因为本来弹幕就是通过cid请求获取的

那我自己试试吧。

**Comment by itKelis** [comment]
> > > 或者用 rust 写 MPV 的 [C plugin](https://lib.rs/crates/mpv-client)
> > 
> > 
> > 只能让那个danmu2ass的作者支持一下通过cid获取视频弹幕了，因为本来弹幕就是通过cid请求获取的
> 
> 那我自己试试吧。

失去了网页端的脚本支持，你也不能简单方便的使用mpv看视频吧

**Comment by itKelis** [comment]
> > > 或者用 rust 写 MPV 的 [C plugin](https://lib.rs/crates/mpv-client)
> > 
> > 
> > 只能让那个danmu2ass的作者支持一下通过cid获取视频弹幕了，因为本来弹幕就是通过cid请求获取的
> 
> 那我自己试试吧。

是可以的，在 [gwy15/danmu2ass/ ](https://github.com/gwy15/danmu2ass/blob/main/src/cli.rs) 第258行是使用cid获取弹幕文件的，可以让作者支持直接通过cid获取弹幕文件，就可以使用了

**Comment by skbeh** [comment]
@itKelis 用 rust 写了一个支持直接加载链接的测试版，要求 PATH 中存在最新代码库构建的 danmu2ass：
https://github.com/skbeh/mpv-danmaku

**Comment by itKelis** [comment]
> @itKelis 用 rust 写了一个支持直接加载链接的测试版，要求 PATH 中存在最新代码库构建的 danmu2ass： https://github.com/skbeh/mpv-danmaku

但是问题是，从网页端调用mpv的参数并不存在bilibili.com的domain，只存在音视频流源地址，以bilivideo.com或bilivideo.cn开头的域名，与单独传递的参数，cid

**Comment by itKelis** [comment]
> @itKelis 用 rust 写了一个支持直接加载链接的测试版，要求 PATH 中存在最新代码库构建的 danmu2ass： https://github.com/skbeh/mpv-danmaku

等我有时间去修改一下https://github.com/gwy15/danmu2ass，暴露出直接使用cid的接口就可以了

**Comment by itKelis** [comment]
> @itKelis 用 rust 写了一个支持直接加载链接的测试版，要求 PATH 中存在最新代码库构建的 danmu2ass： https://github.com/skbeh/mpv-danmaku

不过他的二进制文件比python转译的二进制文件还大啊，因为异步加载，同时单个视频的数据量真的非常小，性能问题是可以忽略不计的，还不如你下载字幕文件的网络延时高，就算费了很大劲修改了https://github.com/LuckyPuppy514/Play-With-MPV 支持的网页脚本，也修改了我这个插件，最终的加载效果也是肉眼不可见的。如果你希望使用二进制文件，python转译的也不是不行（文件大小还比他的程序小点）。

**Comment by itKelis** [comment]
> 

> > @itKelis 用 rust 写了一个支持直接加载链接的测试版，要求 PATH 中存在最新代码库构建的 danmu2ass： https://github.com/skbeh/mpv-danmaku
> 
> 不过他的二进制文件比python转译的二进制文件还大啊，因为异步加载，同时单个视频的数据量真的非常小，性能问题是可以忽略不计的，还不如你下载字幕文件的网络延时高，就算费了很大劲修改了https://github.com/LuckyPuppy514/Play-With-MPV 支持的网页脚本，也修改了我这个插件，最终的加载速度提升也是肉眼不可见的。如果你希望使用二进制文件，python转译的也不是不行（文件大小还比他的程序小点）。

**Comment by itKelis** [comment]
> > 
> 
> > > @itKelis 用 rust 写了一个支持直接加载链接的测试版，要求 PATH 中存在最新代码库构建的 danmu2ass： https://github.com/skbeh/mpv-danmaku
> > 
> > 
> > 不过他的二进制文件比python转译的二进制文件还大啊，因为异步加载，同时单个视频的数据量真的非常小，性能问题是可以忽略不计的，还不如你下载字幕文件的网络延时高，就算费了很大劲修改了https://github.com/LuckyPuppy514/Play-With-MPV 支持的网页脚本，也修改了我这个插件，最终的加载速度提升也是肉眼不可见的。如果你希望使用二进制文件，python转译的也不是不行（文件大小还比他的程序小点）。

**Comment by skbeh** [comment]
@itKelis 我的方案是使用 https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv，配合 `mpv-handler`。

**Comment by skbeh** [comment]
@itKelis 你的可执行文件是怎么打包的？pyinstaller 很难达到这个大小。

**Comment by itKelis** [comment]
> @itKelis 我的方案是使用 [https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv，配合](https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88) `mpv-handler`。

我知道你的脚本什么意思，我也可以转写成lua，但是mpv没有获取 bilibili.com/bv 的网址啊，只获得了最终音视频源地址
![image](https://user-images.githubusercontent.com/14844805/208221515-e21cfe24-37af-4b3a-bfdc-9b87aeea7913.png)

**Comment by itKelis** [comment]
> @itKelis 你的可执行文件是怎么打包的？pyinstaller 很难达到这个大小。

我是完全使用python自带的标准库编写的，为了尽可能的提升计算速度

**Comment by itKelis** [comment]
> @itKelis 你的可执行文件是怎么打包的？pyinstaller 很难达到这个大小。

你但凡加个第三方库，他的文件大小最小也会到十几mb

**Comment by itKelis** [comment]
> > @itKelis 你的可执行文件是怎么打包的？pyinstaller 很难达到这个大小。
> 
> 你但凡加个第三方库，他的文件大小最小也会到十几mb，同时使用python标准库有着最佳的性能

**Comment by skbeh** [comment]
> > @itKelis 我的方案是使用 [https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv，配合](https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88) `mpv-handler`。
> 
> 我知道你的脚本什么意思，我也可以转写成lua，但是mpv没有获取 bilibili.com/bv 的网址啊，只获得了最终音视频源地址 ![image](https://user-images.githubusercontent.com/14844805/208221515-e21cfe24-37af-4b3a-bfdc-9b87aeea7913.png)

https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88 直接传的网页 URL。

**Comment by skbeh** [comment]
> > @itKelis 你的可执行文件是怎么打包的？pyinstaller 很难达到这个大小。
> 
> 我是完全使用python自带的标准库编写的，为了尽可能的提升计算速度

我这里 release build 的 danmu2ass，strip 完大小 5.7M。

**Comment by itKelis** [comment]
> > > @itKelis 我的方案是使用 [https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv，配合](https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88) `mpv-handler`。
> > 
> > 
> > 我知道你的脚本什么意思，我也可以转写成lua，但是mpv没有获取 bilibili.com/bv 的网址啊，只获得了最终音视频源地址 ![image](https://user-images.githubusercontent.com/14844805/208221515-e21cfe24-37af-4b3a-bfdc-9b87aeea7913.png)
> 
> https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88 直接传的网页 URL。

我觉得吧，你这个还要手动导出cookie，还不如直接把解析的工作放在网页脚本端，一键就能播放了

**Comment by skbeh** [comment]
> 我觉得吧，你这个还要手动导出cookie，还不如直接把解析的工作放在网页脚本端，一键就能播放了
主要是网页脚本解析缺乏通用性，需要对每个网站分别处理。
而且 https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88 支持在链接中传递 cookies。

**Comment by itKelis** [comment]
> > 我觉得吧，你这个还要手动导出cookie，还不如直接把解析的工作放在网页脚本端，一键就能播放了
> 
> 主要是网页脚本解析缺乏通用性，需要对每个网站分别处理。 而且 https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88 支持在链接中传递 cookies。

这个脚本也没有通用性啊，他的match已经写死了
![image](https://user-images.githubusercontent.com/14844805/208221955-9c7fd60d-8bf8-494f-96b0-444d934049cb.png)

**Comment by itKelis** [comment]
> > 我觉得吧，你这个还要手动导出cookie，还不如直接把解析的工作放在网页脚本端，一键就能播放了
> 
> 主要是网页脚本解析缺乏通用性，需要对每个网站分别处理。 而且 https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv%EF%BC%8C%E9%85%8D%E5%90%88 支持在链接中传递 cookies。

有很多网站他是动态加载的，单单获取一个域名可能只能看到第一集，其他剧集也看不到了，所以应该还是网页脚本端进行详细解析比较好

**Comment by skbeh** [comment]
> 这个脚本也没有通用性啊，他的match已经写死了 ![image](https://user-images.githubusercontent.com/14844805/208221955-9c7fd60d-8bf8-494f-96b0-444d934049cb.png)

但是 match 可以直接任意加。
我可以去问问原作者为什么不加入所有 ytdl 支持的网站。

**Comment by skbeh** [comment]
> 有很多网站他是动态加载的，单单获取一个域名可能只能看到第一集，其他剧集也看不到了，所以应该还是网页脚本端进行详细解析比较好

举个例子？
另外，我一般还是习惯复制+粘贴 URL。

**Comment by itKelis** [comment]
> > 这个脚本也没有通用性啊，他的match已经写死了 ![image](https://user-images.githubusercontent.com/14844805/208221955-9c7fd60d-8bf8-494f-96b0-444d934049cb.png)
> 
> 但是 match 可以直接任意加。 我可以去问问原作者为什么不加入所有 ytdl 支持的网站。

我将倒数第二个www.bilibili.com/video/*直接粗暴的改成www.bilibili.com/*
随后打开一个番剧https://www.bilibili.com/bangumi/play/ep424609?from_spmid=666.25.episode.0&from_outer_spmid=666.4.septincome.2 他也没有生效

**Comment by itKelis** [comment]
> > > 这个脚本也没有通用性啊，他的match已经写死了 ![image](https://user-images.githubusercontent.com/14844805/208221955-9c7fd60d-8bf8-494f-96b0-444d934049cb.png)
> > 
> > 
> > 但是 match 可以直接任意加。 我可以去问问原作者为什么不加入所有 ytdl 支持的网站。
> 
> 我将倒数第二个www.bilibili.com/video/*_直接粗暴的改成www.bilibili.com/*
后面带有星号，github不显示
 随后打开一个番剧https://www.bilibili.com/bangumi/play/ep424609?from_spmid=666.25.episode.0&from_outer_spmid=666.4.septincome.2 他也没有生效

**Comment by skbeh** [comment]
> 他也没有生效

你还需要改 `MATCHER`
不过我觉得去掉 MATCH 视频 URL 的机制也无所谓。

**Comment by itKelis** [comment]
> > 他也没有生效
> 
> 你还需要改 `MATCHER` 不过我觉得去掉 MATCH 视频 URL 的机制也无所谓。

我是不认为yt-dl能够解析动态的视频网站，你可以试试看爱奇艺，腾讯视频，ddys.tv等，现在的视频网站动态加载才是主流

**Comment by itKelis** [comment]
> > > 他也没有生效
> > 
> > 
> > 你还需要改 `MATCHER` 不过我觉得去掉 MATCH 视频 URL 的机制也无所谓。
> 
> 我是不认为yt-dl能够解析动态的视频网站，你可以试试看爱奇艺，腾讯视频，ddys.tv等，现在的视频网站动态加载才是主流

如果希望支持这些网站，人工编写解析规则还是必要的操作

**Comment by skbeh** [comment]
> > > > 这个脚本也没有通用性啊，他的match已经写死了 ![image](https://user-images.githubusercontent.com/14844805/208221955-9c7fd60d-8bf8-494f-96b0-444d934049cb.png)
> > > 
> > > 
> > > 但是 match 可以直接任意加。 我可以去问问原作者为什么不加入所有 ytdl 支持的网站。
> > 
> > 
> > 我将倒数第二个www.bilibili.com/video/__直接粗暴的改成www.bilibili.com/_
> > 后面带有星号，github不显示
> > 随后打开一个番剧https://www.bilibili.com/bangumi/play/ep424609?from_spmid=666.25.episode.0&from_outer_spmid=666.4.septincome.2 他也没有生效

这个是会员番剧，需要大会员账号的 cookies。

**Comment by itKelis** [comment]
> > 随后打开一个番剧https://www.bilibili.com/bangumi/play/ep424609 他也没有生效
> 
> 这个是会员番剧，需要大会员账号的 cookies。

https://www.bilibili.com/bangumi/play/ep691423?from_spmid=666.25.episode.0&from_outer_spmid=666.4.schedule.3 你随便找个番剧，都是不行的

**Comment by skbeh** [comment]
> https://www.bilibili.com/bangumi/play/ep691423 你随便找个番剧，都是不行的
我这里改完可以。

**Comment by itKelis** [comment]
> > https://www.bilibili.com/bangumi/play/ep691423 你随便找个番剧，都是不行的
> 
> 我这里改完可以。

那我就看看怎么改吧

**Comment by skbeh** [comment]
你上面说的那些网站都是使用 URL 区分不同视频的，爱奇艺和 ddys.tv yt-dlp 没适配。

**Comment by skbeh** [comment]
@itKelis 我改了一版：https://github.com/skbeh/play-with-mpv

**Comment by itKelis** [comment]
> @itKelis 我改了一版：https://github.com/skbeh/play-with-mpv

我怎么感觉使用yt-dl解析也太慢了吧，等了好几秒才解析出来
我没使用过rust，尝试编译你的程序一直都不成功，要不你提个pull request?还是你自己新建一个仓库？
我觉得yt-dl也是python程序吧，如果想要顺利解析视频，我觉得反正是无论如何都躲不开python的了。

而且现在js的解析速度比python快的多，把访问api的主要工作放在网页端应该效率更高

**Comment by skbeh** [comment]
@itKelis MPV 的 C plugin 仅支持 Linux。

**Comment by itKelis** [comment]
> @itKelis MPV 的 C plugin 仅支持 Linux。

那这个又违背了mpv跨平台的初衷啊，要不你新开一个仓库？
主要是我真的不觉得把python替换成二进制文件有什么必要性，如果你是windows用户还能够考虑考虑，但是在linux下，python几乎已经成为系统的一部分，很多软件的依赖都用到python，也没有必要脱离python，更何况你所依赖的yt-dl同样也是一个python脚本。

**Comment by skbeh** [comment]
@itKelis 我确实开了个新仓库。
使用二进制主要是因为 rust 方便打包和管理。

**Comment by itKelis** [comment]
> @itKelis 我确实开了个新仓库。 使用二进制主要是因为 rust 方便打包和管理。

是 https://github.com/skbeh/mpv-danmaku 吗，把md文件写了，我这里写个相关仓库嘛，对不起这个rust我真的看不懂，现在我也有事情要做，没有时间学习rust，等我学会rust再好好理一理看看怎么样子修改吧
