### ISSUE TITLE
希望您可以在readme写一下如何客制化参数。。

### ISSUE THREAD

**Issue by CBEpt** [itKelis/MPV-Play-BiliBili-Comments#7]
热门视频很多弹幕都重叠在一起了。。
有的视频弹幕速度飘得太快了。。作为小白，没学过这些语言是一个都不会改。。

**Comment by itKelis** [comment]
热门视频是指竖屏吗，ass弹幕的显示范围就是视频画面，无法在黑边显示弹幕，所以用这个插件播放竖屏视频，弹幕问题是解决不了的。
如果确实需要客制化参数，最基本的几个参数和注释我已经添加到了main.lua，可以重新下载一下main.lua
还有一个弹幕重叠的原因可能是分辨率小于1920x1080，目前弹幕的行数是根据1920x1080这个分辨率计算出来的，可以修改一下新的main.lua中1920x1080这个数值为你的屏幕分辨率
