### ISSUE TITLE
想问下，每次拉起的字幕是b站自带的，如果我要拉起弹幕的话怎么改，求解，谢谢

### ISSUE THREAD

**Issue by zenx0x** [itKelis/MPV-Play-BiliBili-Comments#8]

**Comment by itKelis** [comment]
显示/隐藏弹幕请按 b 键

**Comment by itKelis** [comment]
> ![image](https://user-images.githubusercontent.com/56068289/215642944-3bde6cca-523e-4f55-a8a8-22bdbddea4fe.png)
> 
> 比如这个，「第一视角」AITO问界M5 - 鸿蒙车机太惊艳，开起来调教也成熟！_哔哩哔哩_bilibili 视频号：BV1Yr4y1B7Dn 字幕链接：https://www.lckp.top/common/bilibili/jsonToSrt/url=https://i0.hdslb.com/bfs/ai_subtitle/prod/76719962954637674609574e1e932b329a0063bd581fa2e542&lan=ai-zh
> 
> ![image](https://user-images.githubusercontent.com/56068289/215644917-a0a4ab25-3378-4c59-9767-5b10f66b405b.png) 按b成功拉起了字幕，但都是b站自带的字幕，不是弹幕。PS:我的关于mpv.conf里面的subtitle这样的字幕设置已经全部关闭了

这个好像是因为Play-With-MPV这个脚本默认加载字幕，而不是加载弹幕了，让我研究研究怎么解决。你看看能不能降级这个脚本

**Comment by zenx0x** [comment]
OK，谢谢，我先这样用吧，其实加载弹幕并不是一个强的需求。

**Comment by orz12** [comment]
> OK，谢谢，我先这样用吧，其实加载弹幕并不是一个强的需求。

我试了一下 确实在设置中把字幕关掉就可以正常加载弹幕，也不需要降级什么的
![image](https://github.com/itKelis/MPV-Play-BiliBili-Comments/assets/17450420/9332ab4a-f963-45df-99f6-82741a12575c)

**Comment by limoren123** [comment]
> OK，谢谢，我先这样用吧，其实加载弹幕并不是一个强的需求。

我个人发现的情况是如果解压MPV播放器文件夹在C:\Program Files或者C:\Program Files (x86)，会因为权限问题 无法更新bilibili.ass文件导致一直显示的默认的测试弹幕，直接放到C:\mpvnet，完美解决这个问题。

同理中文目录好像也不行

**Comment by itKelis** [comment]
> > OK，谢谢，我先这样用吧，其实加载弹幕并不是一个强的需求。
> 
> 我个人发现的情况是如果解压MPV播放器文件夹在C:\Program Files或者C:\Program Files (x86)，会因为权限问题 无法更新bilibili.ass文件导致一直显示的默认的测试弹幕，直接放到C:\mpvnet，完美解决这个问题。
> 
> 同理中文目录好像也不行

不建议放在c盘，c盘需要管理员权限比较麻烦，建议放在其他盘或者放在%appdata%目录中。

同时路径也不建议带有中文、空格或其他特殊字符
